services:
  runner:
    image: local/self-hosted-runner:local
    build:
      context: ./Docker Image
      dockerfile: Dockerfile
    restart: always
    environment:
      REPO: ${REPO:?REPO is required}
      REG_TOKEN: ${REG_TOKEN:?REG_TOKEN is required}
      NAME: ${NAME:?NAME is required}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
